version: "3.8"

services:
  db:
    image: postgres:14.5
    container_name: twitter-clone-postgres
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: twitter-user
      POSTGRES_PASSWORD: twitter-password
      POSTGRES_DB: twitter
    restart: "no"